import pyodbc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox

from admin.global_variables import GlobalStatic


class policeRegistrationPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 803)
        MainWindow.setStyleSheet("background-color: rgb(191, 140, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(400, 80, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.heading.setObjectName("heading")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 40, 1151, 711))
        self.graphicsView_2.setStyleSheet("background-color: rgb(59, 43, 1);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(35, 31, 1161, 731))
        self.graphicsView.setStyleSheet("background-color: rgb(233, 255, 246);")
        self.graphicsView.setObjectName("graphicsView")
        self.d_id = QtWidgets.QLabel(self.centralwidget)
        self.d_id.setGeometry(QtCore.QRect(180, 200, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_id.setFont(font)
        self.d_id.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_id.setObjectName("d_id")
        self.d_name = QtWidgets.QLabel(self.centralwidget)
        self.d_name.setGeometry(QtCore.QRect(740, 190, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_name.setFont(font)
        self.d_name.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_name.setObjectName("d_name")
        self.cith_y = QtWidgets.QLabel(self.centralwidget)
        self.cith_y.setGeometry(QtCore.QRect(180, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cith_y.setFont(font)
        self.cith_y.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.cith_y.setObjectName("cith_y")
        self.d_place = QtWidgets.QLabel(self.centralwidget)
        self.d_place.setGeometry(QtCore.QRect(180, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_place.setFont(font)
        self.d_place.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_place.setObjectName("d_place")
        self.d_phone = QtWidgets.QLabel(self.centralwidget)
        self.d_phone.setGeometry(QtCore.QRect(740, 300, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_phone.setFont(font)
        self.d_phone.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_phone.setObjectName("d_phone")
        self.d_exp = QtWidgets.QLabel(self.centralwidget)
        self.d_exp.setGeometry(QtCore.QRect(740, 420, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_exp.setFont(font)
        self.d_exp.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_exp.setObjectName("d_exp")
        self.dBack = QtWidgets.QPushButton(self.centralwidget)
        self.dBack.setGeometry(QtCore.QRect(670, 660, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dBack.setFont(font)
        self.dBack.setStyleSheet("background-color: rgb(217, 217, 217);\n"
                                 "")
        self.dBack.setObjectName("dBack")
        self.dSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.dSubmit.setGeometry(QtCore.QRect(350, 660, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dSubmit.setFont(font)
        self.dSubmit.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dSubmit.setObjectName("dSubmit")
        self.pid = QtWidgets.QLineEdit(self.centralwidget)
        self.pid.setGeometry(QtCore.QRect(180, 240, 301, 41))
        self.pid.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pid.setObjectName("did")
        self.pPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.pPhone.setGeometry(QtCore.QRect(740, 340, 301, 41))
        self.pPhone.setStyleSheet("background-color: rgb(217, 217, 217);\n""")
        self.pPhone.setObjectName("dPhone")
        self.pPlace = QtWidgets.QLineEdit(self.centralwidget)
        self.pPlace.setGeometry(QtCore.QRect(180, 460, 301, 41))
        self.pPlace.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pPlace.setObjectName("dPlace")
        self.pAge = QtWidgets.QLineEdit(self.centralwidget)
        self.pAge.setGeometry(QtCore.QRect(180, 350, 301, 41))
        self.pAge.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pAge.setObjectName("dAge")
        self.pName = QtWidgets.QLineEdit(self.centralwidget)
        self.pName.setGeometry(QtCore.QRect(740, 230, 301, 41))
        self.pName.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pName.setObjectName("dName")

        self.pExp = QtWidgets.QLineEdit(self.centralwidget)
        self.pExp.setGeometry(QtCore.QRect(740, 460, 301, 41))
        self.pExp.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pExp.setObjectName("dExp")
        self.d_Email = QtWidgets.QLabel(self.centralwidget)
        self.d_Email.setGeometry(QtCore.QRect(180, 530, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_Email.setFont(font)
        self.d_Email.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_Email.setObjectName("d_Email")
        self.d_password = QtWidgets.QLabel(self.centralwidget)
        self.d_password.setGeometry(QtCore.QRect(740, 530, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_password.setFont(font)
        self.d_password.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_password.setObjectName("d_password")
        self.pMal = QtWidgets.QLineEdit(self.centralwidget)
        self.pMal.setGeometry(QtCore.QRect(180, 570, 301, 41))
        self.pMal.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pMal.setObjectName("dMal")
        self.pPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.pPassword.setGeometry(QtCore.QRect(740, 570, 301, 41))
        self.pPassword.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.pPassword.setObjectName("dPassword")
        self.graphicsView.raise_()
        self.graphicsView_2.raise_()
        self.heading.raise_()
        self.d_id.raise_()
        self.d_name.raise_()
        self.cith_y.raise_()
        self.d_place.raise_()
        self.d_phone.raise_()
        self.d_exp.raise_()
        self.dBack.raise_()
        self.dSubmit.raise_()
        self.pid.raise_()
        self.pPlace.raise_()
        self.pAge.raise_()
        self.pName.raise_()
        self.pPhone.raise_()
        self.pExp.raise_()
        self.d_Email.raise_()
        self.d_password.raise_()
        self.pMal.raise_()
        self.pPassword.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.dBack.clicked.connect(lambda: self.rdclosescr(MainWindow))
        self.dSubmit.clicked.connect(self.polRegisterData)

    def rdclosescr(self, MainWindow):
        MainWindow.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heading.setText(_translate("MainWindow", "    Police Registration"))
        self.d_id.setText(_translate("MainWindow", "   Police_Id"))
        self.d_name.setText(_translate("MainWindow", "   Police_Name"))
        self.cith_y.setText(_translate("MainWindow", "  Age"))
        self.d_place.setText(_translate("MainWindow", "  Place"))
        self.d_phone.setText(_translate("MainWindow", "  Phone"))
        self.d_exp.setText(_translate("MainWindow", "  Experience"))
        self.dBack.setText(_translate("MainWindow", "<- BACK"))
        self.dSubmit.setText(_translate("MainWindow", "SUBMIT"))
        self.d_Email.setText(_translate("MainWindow", "  E-Mail"))
        self.d_password.setText(_translate("MainWindow", "  Password"))

    def polRegisterData(self):
        p_id = self.pid.text()
        p_name = self.pName.text()
        p_age = self.pAge.text()
        p_place = self.pPlace.text()
        p_phone = self.pPhone.text()
        p_exp = self.pExp.text()
        p_email = self.pMal.text()
        p_pass = self.pPassword.text()
        # print("ID" + d_id)
        # print("Name" + d_name)
        # print("Age" + d_age)
        # print("place" + d_place)
        # print("phone" + d_phone)
        # print("exp" + d_exp)
        # print("email" + d_email)
        # print("pass" + d_pass)
        # print(f"Obtained hospital id: {GlobalStatic.hospital_id}")

        msg = QMessageBox()

        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        if p_id == "" or p_name == "" or p_age == "" or p_place == "" or p_phone == "" or p_exp == "" or p_email == "" or p_pass == "":
            msg.setText("All Fields need to be filled!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        # elif not self.txt_dexp.get().isdigit():
        #     messagebox.showerror("Error", "Enter valid Experiance!", parent=self.root)
        # #
        # elif not self.txt_dage.get().isdigit():
        #     # messagebox.showerror("Error", "Enter valid Age!", parent=self.root)
        # #
        # elif not self.txt_dphone.get().isdigit():
        #     messagebox.showerror("Error", "Enter valid Phone no!", parent=self.root)
        #
        # elif len(self.txt_dphone.get()) > 10 or len(self.txt_dphone.get()) < 10:
        #     messagebox.showerror("Error", "Enter valid Phone no!", parent=self.root)
        # #
        # elif not (re.search(regex, self.txt_demail.get())):
        #     messagebox.showerror("Error", "Enter valid Email_id!", parent=self.root)

        else:
            try:
                conn = pyodbc.connect(
                "Driver={SQL Server Native Client 11.0};"
                "Server=DESKTOP-EAC2CGC\KAUSHIK;"
                "Database=forensic;"
                "Trusted_Connection=yes;"
            )
                cur = conn.cursor()
                cur.execute("select * from doctor where d_email=?", p_email)
                row = cur.fetchone()
                print(row)
                if row != None:
                    msg.setText("Check Username/Password")
                    msg.setWindowTitle("WARNING")
                    msg.exec_()
                else:
                    cur.execute(
                        "insert into police(p_id,p_name,p_age,p_exp,p_place,p_phone,p_email,p_password, pst_id) values (?,?,?,?,?,?,?,?,?);",
                        (p_id,
                         p_name,
                         p_age,
                         p_place,
                         p_phone,
                         p_exp,
                         p_email,
                         p_pass,
                         GlobalStatic.police_station_id
                         )
                    )
                    msg.setText("Registration SuccessFull!")
                    msg.setWindowTitle("Success")
                    msg.exec_()
                    conn.commit()
                    conn.close()

            except Exception as es:
                print(str(es))
                msg.setText(f"Error Due To: {str(es)}!")
                msg.setWindowTitle("WARNING")
                msg.exec_()
