import pyodbc
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
import re
from admin.global_variables import GlobalStatic


class DoctorRegistrationPage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 803)
        MainWindow.setStyleSheet("background-color: rgb(191, 140, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(400, 80, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.heading.setObjectName("heading")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 40, 1151, 711))
        self.graphicsView_2.setStyleSheet("background-color: rgb(59, 43, 1);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(35, 31, 1161, 731))
        self.graphicsView.setStyleSheet("background-color: rgb(233, 255, 246);")
        self.graphicsView.setObjectName("graphicsView")
        self.d_id = QtWidgets.QLabel(self.centralwidget)
        self.d_id.setGeometry(QtCore.QRect(180, 200, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_id.setFont(font)
        self.d_id.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_id.setObjectName("d_id")
        self.d_name = QtWidgets.QLabel(self.centralwidget)
        self.d_name.setGeometry(QtCore.QRect(740, 190, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_name.setFont(font)
        self.d_name.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_name.setObjectName("d_name")
        self.cith_y = QtWidgets.QLabel(self.centralwidget)
        self.cith_y.setGeometry(QtCore.QRect(180, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.cith_y.setFont(font)
        self.cith_y.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.cith_y.setObjectName("cith_y")
        self.d_place = QtWidgets.QLabel(self.centralwidget)
        self.d_place.setGeometry(QtCore.QRect(180, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_place.setFont(font)
        self.d_place.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_place.setObjectName("d_place")
        self.d_phone = QtWidgets.QLabel(self.centralwidget)
        self.d_phone.setGeometry(QtCore.QRect(740, 300, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_phone.setFont(font)
        self.d_phone.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_phone.setObjectName("d_phone")
        self.d_exp = QtWidgets.QLabel(self.centralwidget)
        self.d_exp.setGeometry(QtCore.QRect(740, 420, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_exp.setFont(font)
        self.d_exp.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_exp.setObjectName("d_exp")
        self.dBack = QtWidgets.QPushButton(self.centralwidget)
        self.dBack.setGeometry(QtCore.QRect(670, 660, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dBack.setFont(font)
        self.dBack.setStyleSheet("background-color: rgb(217, 217, 217);\n"
                                 "")
        self.dBack.setObjectName("dBack")
        self.dSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.dSubmit.setGeometry(QtCore.QRect(350, 660, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dSubmit.setFont(font)
        self.dSubmit.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dSubmit.setObjectName("dSubmit")
        self.did = QtWidgets.QLineEdit(self.centralwidget)
        self.did.setGeometry(QtCore.QRect(180, 240, 301, 41))
        self.did.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.did.setObjectName("did")
        self.dPhone = QtWidgets.QLineEdit(self.centralwidget)
        self.dPhone.setGeometry(QtCore.QRect(740, 340, 301, 41))
        self.dPhone.setStyleSheet("background-color: rgb(217, 217, 217);\n""")
        self.dPhone.setObjectName("dPhone")
        self.dPlace = QtWidgets.QLineEdit(self.centralwidget)
        self.dPlace.setGeometry(QtCore.QRect(180, 460, 301, 41))
        self.dPlace.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dPlace.setObjectName("dPlace")
        self.dAge = QtWidgets.QLineEdit(self.centralwidget)
        self.dAge.setGeometry(QtCore.QRect(180, 350, 301, 41))
        self.dAge.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dAge.setObjectName("dAge")
        self.dName = QtWidgets.QLineEdit(self.centralwidget)
        self.dName.setGeometry(QtCore.QRect(740, 230, 301, 41))
        self.dName.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dName.setObjectName("dName")

        self.dExp = QtWidgets.QLineEdit(self.centralwidget)
        self.dExp.setGeometry(QtCore.QRect(740, 460, 301, 41))
        self.dExp.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dExp.setObjectName("dExp")
        self.d_Email = QtWidgets.QLabel(self.centralwidget)
        self.d_Email.setGeometry(QtCore.QRect(180, 530, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_Email.setFont(font)
        self.d_Email.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_Email.setObjectName("d_Email")
        self.d_password = QtWidgets.QLabel(self.centralwidget)
        self.d_password.setGeometry(QtCore.QRect(740, 530, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.d_password.setFont(font)
        self.d_password.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.d_password.setObjectName("d_password")
        self.dMal = QtWidgets.QLineEdit(self.centralwidget)
        self.dMal.setGeometry(QtCore.QRect(180, 570, 301, 41))
        self.dMal.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dMal.setObjectName("dMal")
        self.dPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.dPassword.setGeometry(QtCore.QRect(740, 570, 301, 41))
        self.dPassword.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.dPassword.setObjectName("dPassword")
        self.graphicsView.raise_()
        self.graphicsView_2.raise_()
        self.heading.raise_()
        self.d_id.raise_()
        self.d_name.raise_()
        self.cith_y.raise_()
        self.d_place.raise_()
        self.d_phone.raise_()
        self.d_exp.raise_()
        self.dBack.raise_()
        self.dSubmit.raise_()
        self.did.raise_()
        self.dPlace.raise_()
        self.dAge.raise_()
        self.dName.raise_()
        self.dPhone.raise_()
        self.dExp.raise_()
        self.d_Email.raise_()
        self.d_password.raise_()
        self.dMal.raise_()
        self.dPassword.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.dBack.clicked.connect(lambda: self.rdclosescr(MainWindow))
        self.dSubmit.clicked.connect(self.DocRegisterData)

    def rdclosescr(self, MainWindow):
        MainWindow.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heading.setText(_translate("MainWindow", "    Doctor Registration"))
        self.d_id.setText(_translate("MainWindow", "   Doctor_Id"))
        self.d_name.setText(_translate("MainWindow", "   Doctor_Name"))
        self.cith_y.setText(_translate("MainWindow", "  Age"))
        self.d_place.setText(_translate("MainWindow", "  Place"))
        self.d_phone.setText(_translate("MainWindow", "  Phone"))
        self.d_exp.setText(_translate("MainWindow", "  Experience"))
        self.dBack.setText(_translate("MainWindow", "<- BACK"))
        self.dSubmit.setText(_translate("MainWindow", "SUBMIT"))
        self.d_Email.setText(_translate("MainWindow", "  E-Mail"))
        self.d_password.setText(_translate("MainWindow", "  Password"))

    def DocRegisterData(self):
        d_id = self.did.text()
        d_name = self.dName.text()
        d_age = self.dAge.text()
        d_place = self.dPlace.text()
        d_phone = self.dPhone.text()
        d_exp = self.dExp.text()
        d_email = self.dMal.text()
        d_pass = self.dPassword.text()
        # print("ID" + d_id)
        # print("Name" + d_name)
        # print("Age" + d_age)
        # print("place" + d_place)
        # print("phone" + d_phone)
        # print("exp" + d_exp)
        # print("email" + d_email)
        # print("pass" + d_pass)
        # print(f"Obtained hospital id: {GlobalStatic.hospital_id}")

        msg = QMessageBox()

        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        if d_id == "" or d_name == "" or d_age == "" or d_place == "" or d_phone == "" or d_exp == "" or d_email == "" or d_pass == "":
            msg.setText("All Fields need to be filled!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        elif not self.dExp.text().isdigit():
            msg.setText("Enter valid Experiance!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        elif not self.dAge.text().isdigit():
            msg.setText("Enter valid Age!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        elif not self.dPhone.text().isdigit():
            msg.setText("Enter valid Phone no!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        elif len(self.dPhone.text()) > 10 or len(self.dPhone.text()) < 10:
            msg.setText("Enter valid Phone no!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        elif not (re.search(regex, self.dMal.text())):
            msg.setText("Enter valid Email_id!")
            msg.setWindowTitle("WARNING")
            msg.exec_()

        else:
            try:
                conn = pyodbc.connect(
                    "Driver={SQL Server Native Client 11.0};"
                    "Server=DESKTOP-EAC2CGC\KAUSHIK;"
                    "Database=forensic;"
                    "Trusted_Connection=yes;"
                )
                cur = conn.cursor()
                cur.execute("select * from doctor where d_email=?", d_email)
                row = cur.fetchone()
                print(row)
                if row != None:
                    msg.setText("Check Username/Password")
                    msg.setWindowTitle("WARNING")
                    msg.exec_()
                else:
                    cur.execute(
                        "insert into doctor(d_id,d_name,d_age,d_exp,d_place,d_phone,d_email,d_password,h_id) values(?,?,?,?,?,?,?,?,?);",
                        (d_id,
                         d_name,
                         d_age,
                         d_place,
                         d_phone,
                         d_exp,
                         d_email,
                         d_pass,
                         GlobalStatic.hospital_id
                         )
                    )
                    msg.setText("Registration SuccessFull!")
                    msg.setWindowTitle("Success")
                    msg.exec_()
                    conn.commit()
                    conn.close()
                    self.clear()

            except Exception as es:
                print(str(es))
                msg.setText(f"Error Due To: {str(es)}!")
                msg.setWindowTitle("WARNING")
                msg.exec_()

    def clear(self):
        self.did.clear(),
        self.dName.clear(),
        self.dAge.clear(),
        self.dPlace.clear(),
        self.dPhone.clear()
        self.dExp.clear()
        self.dMal.clear()
        self.dPassword.clear()