import pyodbc
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
# from global_variables import DbConnector
import re


class StationRegUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 801)
        MainWindow.setMaximumSize(QtCore.QSize(1073, 801))
        MainWindow.setStyleSheet("background-color: rgb(191, 140, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setGeometry(QtCore.QRect(310, 80, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.heading.setFont(font)
        self.heading.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.heading.setObjectName("heading")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 40, 991, 711))
        self.graphicsView_2.setStyleSheet("background-color: rgb(59, 43, 1);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(35, 31, 1001, 731))
        self.graphicsView.setStyleSheet("background-color: rgb(233, 255, 246);")
        self.graphicsView.setObjectName("graphicsView")
        self.s_id = QtWidgets.QLabel(self.centralwidget)
        self.s_id.setGeometry(QtCore.QRect(140, 250, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.s_id.setFont(font)
        self.s_id.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_id.setObjectName("s_id")
        self.s_name = QtWidgets.QLabel(self.centralwidget)
        self.s_name.setGeometry(QtCore.QRect(650, 250, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.s_name.setFont(font)
        self.s_name.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_name.setObjectName("s_name")
        self.s_city = QtWidgets.QLabel(self.centralwidget)
        self.s_city.setGeometry(QtCore.QRect(140, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.s_city.setFont(font)
        self.s_city.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_city.setObjectName("s_city")
        self.s_Email = QtWidgets.QLabel(self.centralwidget)
        self.s_Email.setGeometry(QtCore.QRect(140, 490, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.s_Email.setFont(font)
        self.s_Email.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_Email.setObjectName("s_Email")
        self.s_area = QtWidgets.QLabel(self.centralwidget)
        self.s_area.setGeometry(QtCore.QRect(650, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.s_area.setFont(font)
        self.s_area.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_area.setObjectName("s_area")
        self.s_paddword = QtWidgets.QLabel(self.centralwidget)
        self.s_paddword.setGeometry(QtCore.QRect(660, 490, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.s_paddword.setFont(font)
        self.s_paddword.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_paddword.setObjectName("s_paddword")
        self.sback = QtWidgets.QPushButton(self.centralwidget)
        self.sback.setGeometry(QtCore.QRect(660, 630, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sback.setFont(font)
        self.sback.setStyleSheet("background-color: rgb(217, 217, 217);\n"
                                 "")
        self.sback.setObjectName("sback")
        self.s_submit = QtWidgets.QPushButton(self.centralwidget)
        self.s_submit.setGeometry(QtCore.QRect(310, 630, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.s_submit.setFont(font)
        self.s_submit.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.s_submit.setObjectName("s_submit")
        self.sid = QtWidgets.QLineEdit(self.centralwidget)
        self.sid.setGeometry(QtCore.QRect(140, 290, 301, 41))
        self.sid.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.sid.setObjectName("sid")
        self.semail = QtWidgets.QLineEdit(self.centralwidget)
        self.semail.setGeometry(QtCore.QRect(140, 530, 301, 41))
        self.semail.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.semail.setObjectName("semail")
        self.scity = QtWidgets.QLineEdit(self.centralwidget)
        self.scity.setGeometry(QtCore.QRect(140, 410, 301, 41))
        self.scity.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.scity.setObjectName("scity")
        self.sname = QtWidgets.QLineEdit(self.centralwidget)
        self.sname.setGeometry(QtCore.QRect(650, 290, 301, 41))
        self.sname.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.sname.setObjectName("sname")
        self.sarea = QtWidgets.QLineEdit(self.centralwidget)
        self.sarea.setGeometry(QtCore.QRect(650, 400, 301, 41))
        self.sarea.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.sarea.setObjectName("sarea")
        self.spassword = QtWidgets.QLineEdit(self.centralwidget)
        self.spassword.setGeometry(QtCore.QRect(660, 530, 301, 41))
        self.spassword.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.spassword.setObjectName("spassword")
        self.graphicsView.raise_()
        self.graphicsView_2.raise_()
        self.heading.raise_()
        self.s_id.raise_()
        self.s_name.raise_()
        self.s_city.raise_()
        self.s_Email.raise_()
        self.s_area.raise_()
        self.s_paddword.raise_()
        self.sback.raise_()
        self.s_submit.raise_()
        self.sid.raise_()
        self.semail.raise_()
        self.scity.raise_()
        self.sname.raise_()
        self.sarea.raise_()
        self.spassword.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.sback.clicked.connect(lambda: self.sclosescr(MainWindow))
        self.s_submit.clicked.connect(self.StationRegistration)

    def sclosescr(self, MainWindow):
        MainWindow.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heading.setText(_translate("MainWindow", "  Station Registration"))
        self.s_id.setText(_translate("MainWindow", "   Station_Id"))
        self.s_name.setText(_translate("MainWindow", "   Station_Name"))
        self.s_city.setText(_translate("MainWindow", "  City"))
        self.s_Email.setText(_translate("MainWindow", "  Email_Id"))
        self.s_area.setText(_translate("MainWindow", "  Area"))
        self.s_paddword.setText(_translate("MainWindow", "  Password"))
        self.sback.setText(_translate("MainWindow", "<- BACK"))
        self.s_submit.setText(_translate("MainWindow", "SUBMIT"))

    def StationRegistration(self):
        st_id = self.sid.text()
        st_name = self.sname.text()
        st_area = self.sarea.text()
        st_place = self.scity.text()
        st_email = self.semail.text()
        st_password = self.spassword.text()

        msg = QMessageBox()

        regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        if st_id == "" or st_name == "" or st_area == "" or st_place == "" or st_email == "" or st_password == "":
            msg.setIcon(QMessageBox.Warning)
            msg.setText("All Fields Required!")
            msg.setWindowTitle("Error")
            msg.exec_()
        elif not (re.search(regex, st_email)):
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Enter valid Email_id!")
            msg.setWindowTitle("Error")
            msg.exec_()

        else:
            try:
                conn = pyodbc.connect(
                    "Driver={SQL Server Native Client 11.0};"
                    "Server=DESKTOP-EAC2CGC\KAUSHIK;"
                    "Database=forensic;"
                    "Trusted_Connection=yes;"
                )
                cur = conn.cursor()
                cur.execute("select * from police_station where pst_email=?", st_email)
                row = cur.fetchone()
                print(row)
                if row != None:
                    msg.setText("User Aleady exists!!")
                    msg.setWindowTitle("Error")
                    msg.exec_()
                else:
                    cur.execute(
                        "insert into police_station(pst_id, pst_name, pst_area, pst_place, pst_email, pst_password) values(?,?,?,?,?,?);",
                        (st_id,
                         st_name,
                         st_area,
                         st_place,
                         st_email,
                         st_password,
                         )
                    )
                    msg.setIcon(QMessageBox.Information)
                    msg.setText("Registration SuccessFull!!")
                    msg.setWindowTitle("Success")
                    msg.exec_()
                    conn.commit()
                    conn.close()
                    self.clear()

            except Exception as es:
                print(str(es))
                msg.setIcon(QMessageBox.Warning)
                msg.setText(f"Error Due To: {str(es)}!")
                msg.setWindowTitle("Error")
                msg.exec_()

    def clear(self):
        self.sid.clear()
        self.sname.clear()
        self.sarea.clear()
        self.scity.clear()
        self.semail.clear()
        self.spassword.clear()
